version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin1234
        - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "BeH007826790"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1432:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes: 
        - rabbitmq_data:/var/lib/rabbitmq
    hostname: rabbitmq

  pgadmin:
    container_name: pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@eshop.com
        - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
        - pgadmin_data:/root/.pgadmin

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - elasticSearchConnectionString=http://elasticsearch:9200
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
      - "9000:81" 

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - Urls__GrpcDiscount=http://discount.api:81
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672
      - elasticSearchConnectionString=http://elasticsearch:9200
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:80"
      - "9001:81"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - elasticSearchConnectionString=http://elasticsearch:9200
    depends_on:
      - discountdb
    ports:
      - "8002:80"
      - "9002:81"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OrderingConnectionString=Server=orderdb,1433;Database=OrderDb;User Id=sa;Password=BeH007826790;TrustServerCertificate=true
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672
      - elasticSearchConnectionString=http://elasticsearch:9200
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8003:80"
      - "9003:81" 


  web.shopping.httpaggregator:
    container_name: web.shopping.httpaggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__basket__Destinations__destination0__Address=http://basket.api
      - ReverseProxy__Clusters__catalog__Destinations__destination0__Address=http://catalog.api
      - ReverseProxy__Clusters__orders__Destinations__destination0__Address=http://ordering.api
      - ReverseProxy__Clusters__discount__Destinations__destination0__Address=http://discount.api
      - CatalogUrlHC=http://catalog.api/hc
      - BasketUrlHC=http://basket.api/hc
      - DiscountUrlHC=http://discount.api/hc
      - OrderingUrlHC=http://ordering.api/hc
      - Urls__GrpcBasket=http://basket.api:81
      - Urls__GrpcCatalog=http://catalog.api:81
      - Urls__GrpcOrdering=http://ordering.api:81
      - elasticSearchConnectionString=http://elasticsearch:9200
    depends_on:
      - basket.api
      - catalog.api
      - discount.api
      - ordering.api
    ports:
      - "8080:80"


  webmvc:
    container_name: webmvc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ApiSettings__GatewayAddress=http://web.shopping.httpaggregator
      - WebShoppingHttpaggregatorUrlHC=http://web.shopping.httpaggregator/hc
      - elasticSearchConnectionString=http://elasticsearch:9200
    ports:
      - "8004:80"
    depends_on:
      - web.shopping.httpaggregator
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Catalog HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://catalog.api/hc
      - HealthChecksUI__HealthChecks__1__Name=Basket HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://basket.api/hc
      - HealthChecksUI__HealthChecks__2__Name=Discount HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://discount.api/hc
      - HealthChecksUI__HealthChecks__3__Name=Ordering HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://ordering.api/hc
      - HealthChecksUI__HealthChecks__4__Name=Web httpaggregator HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://web.shopping.httpaggregator/hc
      - HealthChecksUI__HealthChecks__5__Name=Webmvc HTTP Check
      - HealthChecksUI__HealthChecks__5__Uri=http://webmvc/hc 
    depends_on:
      - basket.api
      - discount.api
      - catalog.api
      - ordering.api
      - web.shopping.httpaggregator 
      - webmvc
    ports:
      - "8005:80"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601" 

  grafana:
    container_name: grafana
    ports:
        - "3000:3000"
    volumes:
        - grafana-data:/usr/share/elasticsearch/data
