# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Basket API CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml

  pull_request:
    branches: [ "main" ]
    paths:
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml

env:
  SERVICE: basket.api
  IMAGE: basket.api
  ProjectPath: src/Services/Basket/Basket.API
  RegistryUsername: behdadkardgar
    
jobs:

  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: .github/workflows/template/build-push
      with: 
        service: ${{ env.SERVICE }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ env.RegistryUsername }}
        project_path: ${{ env.ProjectPath }}


